Menu
LeoSight/leosight-eco pull request #6
Opened 2020-01-23 17:45 UTC by Arci224

Menu u ESC, při otevřeném by mělo být automaticky schopné se poté zavřít.

2020-01-23 18:49 UTC, Parado2X approved these changes

2020-01-24 14:17 UTC, RatajVaver reviewed
Ty změny v souboru commands.js nesouvisí s popsaným PR, taky jsou v něm drobné chyby (např. "platné názvy materiálů" místo budov).

Jinak to řešení pro menu by dočasně mohlo být, do budoucna bychom ale mohli udělat vlastní systém modálních oken.

A příště prosím názvy commitů vyplňuj podle toho, co jsi upravil, ať tam není jen "Add files via upload."

2020-01-24 14:42 UTC, RatajVaver requested changes

2020-01-24 14:42 UTC, RatajVaver commented on commands.js
> +                        console.log(`SYNTAX: build [BUDOVA] [X] [Y]\nPlatné názvy budov jsou: ${budovy.join(', ')}`);
Zbytečná duplicita, přehoď celou kontrolu syntaxe na začátek příkazu.

2020-01-24 14:42 UTC, RatajVaver commented on commands.js
> +                    console.log(`SYNTAX: discord [TEXT]`);
Argumenty syntaxe by asi nemuseli být celé velkými písmeny, kapitálky postačí.

2020-01-24 14:42 UTC, RatajVaver commented on commands.js
> +                if(cmd.join(' ') == '') {
Raději vyřešit pomocí `length` a můžeš to hodit ještě před shift.

2020-01-24 15:18 UTC, RatajVaver approved these changes

2020-01-24 15:21 UTC, merged