Skaly
LeoSight/leosight-eco pull request #7
Opened 2020-01-23 18:35 UTC by Parado2X

Pridané skaly
Pridaný obrázok skál

2020-01-23 20:51 UTC, Arci224 approved these changes

2020-01-24 00:08 UTC, RatajVaver commented
Když pominu to, že jsme skály nijak zvlášť neprobrali na Discordu (bylo by vhodné každou feature předem probrat, zda má cenu ji přidávat, zda to ostatních chtějí), tak máš v navrhovaném kódu dost chyb.

Například umožňuješ na server-side smazat skálu přes normální funkci destroy za 1 energii, ale přidáváš pak ještě vlastní funkci destroyRock (která se jako jediná vykresluje na client-side), to lze samozřejmě zneužít, ale hlavně jde o zbytečnou duplicitu.

Dále by celkově zničení skály (ať už je zamýšleno po obsazení pole nebo při obsazení pole) šlo zakomponovat do existujících funkcí (rozšířit je o větší variabilitu).

Největší problém okomentuji zvlášť, aby bylo vidět, na co si příště rozhodně dávat pozor (viz další komentář ke konkrétní části kódu).

Na druhou stranu musím aspoň pochválit, že jsi si dal pozor i na detaily, jako např. že HQ nelze založit tam, kde je skála.

2020-01-24 00:14 UTC, RatajVaver requested changes

2020-01-24 00:14 UTC, RatajVaver commented on index.js
> +                    io.emit('cell', x, y, null, null, null, null);
Touto částí kódu vlastně říkáš serveru, aby současně odebral skálu. Databázi pak říkáš, že čtverec XY nyní vlastní hráč, který zničil skálu a že tam skála nyní nebude. Na závěr na klient posíláš informaci s tím, že se zničila skála a že ji nikdo nevlastní (navíc i bez ohledu předchozího možného vlastníka). Hráč tedy může vidět něco jiného, než je realita na serveru a ještě k tomu po restartu serveru může nastat ještě odlišná situace při znovunačtení z databáze.

2020-01-24 22:02 UTC, closed without merging